classDiagram
    class Todo {
        -String id
        -String title
        -String accountId
        +Account(String id,title,accounId)
    }

    class TodoListSystem {
        -Todo[] todoList
        +void createTodo()
        +Todo[] loadTodosByAccount(Account[])
        +void deleteTodo()
    }

    class Account {
        -String AccountId
        -String AccountPassword
        +Account(String id, String password)
        +boolean login(String id, password)
        +getAccountId
        +getAccountPassword

    }

    class AccountSystem {
        -Account[] accountList
        -Account currentLogin
        +void addAccount()
        +Account getUserAccount
        +void login(String id, String password)
        +void logout(String id, String password)
    }

    class InputHandler {
        +String getStringInput(String type)
    }

    class ConsoleTools {
        +void clear()
    }

    class Main {
        +void main()
    }

    Main --> AccountSystem : creates
    Main --> TodoListSystem : creates
    Main --> InputHandler : uses
    Main --> ConsoleTools : uses
    TodoListSystem --> Todo : manages
    AccountSystem --> Account : manages
    Todo --> Account : belongs to